### ISSUE TITLE
Tambahin deskripi dependensi dong mas kalo bisa hehe

### ISSUE THREAD

**Issue by mohamad-supangat** [elianiva/dotfiles#2]
Ketika saya mencoba dotfile nvim ternyata butuh beberapa dependensi pada folder ~/repos nah, tek coba coba sampe saat ini belumm sempet sampe jadi hehe,

terimakasih mas dotfile nya, membantu sekali

**Comment by elianiva** [comment]
sebenernya ini cuma buat backup sih.. gaada niatan buat dipake orang lain

itu di bagian mana ya btw?

**Comment by mohamad-supangat** [comment]
coba mas 

- https://github.com/elianiva/dotfiles/blob/2644662db0b2b4b537f6d51b7b344b1345f2d7b3/nvim/.config/nvim/lua/plugins/_packer.lua#L87
- https://github.com/elianiva/dotfiles/blob/2644662db0b2b4b537f6d51b7b344b1345f2d7b3/nvim/.config/nvim/lua/plugins/_packer.lua#L181

kemaren udahtek ganti repo official sih, tapi ada yang  minta lagi ke /home/elianiva, bukan ke /home/{user ku}

**Comment by elianiva** [comment]
`nvim-treesitter/nvim-treesitter`

`nvim-telescope/telescope.nvim`
