### ISSUE TITLE
[REQUEST] I love your desktop but impossible to clone it

### ISSUE THREAD

**Issue by linuxmobile** [elianiva/dotfiles#3]
Hi friend. I'm linuxmobile. I love your work and i want to install your dotfiles, but it's hard to understand what r u using right now. Can you try to help doing a better dotfiles repo?

**Comment by elianiva** [comment]
do you need anything in particular? If you give me like a list of things that you want from my configs, I can tell you what you need to do.

**Comment by linuxmobile** [comment]
> 
> 
> do you need anything in particular? If you give me like a list of things that you want from my configs, I can tell you what you need to do.

Oww, fast answer. I love this https://raw.githubusercontent.com/elianiva/dotfiles/master/preview.png desktop... Can you try to do a installer .sh?

**Comment by elianiva** [comment]
no need for a script, it's dead simple.

- build the latest awesomewm and neovim, the instructions are available in their repo
- move `awesome/.config/awesome` folder to your `~/.config/awesome/`
- move `nvim/.config/nvim` folder to your `~/.config/nvim/`
- go to `~/.config/nvim/lua/plugins/_packer.lua` find and replace `~/repos/telescope.nvim` to `nvim-telescope/telescope.nvim`

**Comment by linuxmobile** [comment]
>     * `pos/telescope.nvim` to `nvim-telescope/telescope.nvim`

Ok, thx u!!! your web is so cute!!!
