### ISSUE TITLE
[Request] Try to add "install dependencies"

### ISSUE THREAD

**Issue by linuxmobile** [elianiva/dotfiles#4]
Hi, today I tried all day to get your desktop but no luck. Maybe you can add to README.md an "**Install dependencies**" like this (https://github.com/linuxmobile/runarch/blob/master/bspwm.sh). I use that to install my bspwm, or my openbox desktop.

When i copy your files (like awesome and nvim) I get too many errors about widget.lua}

And i miss fonts and similar things. **I know I'm asking too much, but your desktop is beautiful**

**Comment by elianiva** [comment]
are you sure you're using the latest awesomewm? not the stable version, but build it from the repo

**Comment by linuxmobile** [comment]
> not the stable version, but

I'm using yay -S awesome-git

**Comment by elianiva** [comment]
you should be fine, there's no dependency for awesomewm and I couldn't figure out the error without a clear error message.
