### ISSUE TITLE
How to config the "scope line"?

### ISSUE THREAD

**Issue by lee-shun** [elianiva/dotfiles#5]
Hello!

I am from Reddit! I saw your record about to draw the "scope line" in the .ts file? 
how could you do that? Could you show me some information or steps to config?

Thank You!

By the way, this is your awesome video~ 
[https://streamable.com/mp04i8](https://streamable.com/mp04i8)

**Comment by elianiva** [comment]
It's now officially supported by indent-blankline.nvim, so it's much much easier to use. See: https://github.com/lukas-reineke/indent-blankline.nvim#with-context-indent-highlighted-by-treesitter

**Comment by lee-shun** [comment]
Thank you for your quick reply! But I want to use some ting like yours: "the level line+ the vertical line'.... So you know : )

**Comment by lee-shun** [comment]
![image](https://user-images.githubusercontent.com/46647235/140248615-c87de425-beda-4ce8-a8c4-2a6fdaa3c4d1.png)
as you can see, I already using this indentLine feature, but I want the "level line under the current scope.

**Comment by elianiva** [comment]
right, that one, unfortunately I deleted the code a while ago because it was too inconsistent and annoying to use. I'll probably make a PR for the plugin in the future when I figured out how to make it more consistent.

**Comment by lee-shun** [comment]
Great, you will be my hero if you do so...
And I am really excited about this new feature! 
Thank you!

**Comment by lee-shun** [comment]
For your convenience, I found the commit that might content the features [https://github.com/elianiva/dotfiles/tree/4bdf9140dbc668d892b24a7f9621c12b1ea06462](https://github.com/elianiva/dotfiles/tree/4bdf9140dbc668d892b24a7f9621c12b1ea06462)
