### ISSUE TITLE
[question] I'm puzzled that the `vim.api.nvim_buf_set_keymap` can not work

### ISSUE THREAD

**Issue by lqfxz520** [elianiva/dotfiles#6]
Parameter 5:  Accept `callback` as key is unknown key, An error occurs when executing code
Can you tell me why?
``` lua
local map = vim.api.nvim_buf_set_keymap
M.lsp_mappings = function(bufnr)
  map(bufnr, "i", "<C-s>", "", {
    callback = vim.lsp.buf.signature_help,
    desc = "Trigger signature help from the language server",
    noremap = true,
    silent = true,
  })
end
```

**Comment by elianiva** [comment]
what neovim version do you have?

**Comment by lqfxz520** [comment]
The version number of Neovim is 6.1, so it needs a higher version number than neovim, right？

**Comment by elianiva** [comment]
yes, it's a relatively new API from ~13 days ago

**Comment by lqfxz520** [comment]
I see. Your code is very useful to me
Thank you for your answer.

**Comment by lqfxz520** [comment]
Hello, @elianiva 
method `M.workspace_symbols` is called in file `modules/lsp/mappings.lua`, but method `M.workspace_symbols` is defined in file `plugins/telescope.lua`. 
This is supposed to be a module variable, right? Why can it be used in file `modules/lsp/mappings.lua`
``` lua
  -- path: plugins/telescope.lua
  M.workspace_symbols = function()
    require("telescope.builtin").lsp_workspace_symbols {
      path_display = { "absolute" },
    }
  end

  -- path: modules/lsp/mappings.lua
  map(bufnr, "n", "<Leader>gs", "", {
    callback = M.workspace_symbols,
    desc = "Find workspace symbols using Telescope",
    noremap = true,
    silent = true,
  })
```

**Comment by elianiva** [comment]
you need to do `require("plugins.telescope").workspace_symbols` instead
